#!/bin/sh

export LANG=C
export LC_ALL=C
SERVEROSTYPE="$(uname -s | tr '[ABCDEFGHIJKLMNOPQRSTUVWXYZ/]' '[abcdefghijklmnopqrstuvwxyz_]')"	# This systems operating system in lowercase
MACHINEDOTS="$(uname -n)"

echo "client $MACHINEDOTS.$SERVEROSTYPE linux"
echo "[date]"
date
echo "[uname]"
uname -rsmn
echo "[osversion]"
if [ -x /bin/lsb_release ]; then
	/bin/lsb_release -r -i -s | xargs echo
	/bin/lsb_release -a 2>/dev/null
elif [ -x /usr/bin/lsb_release ]; then
	/usr/bin/lsb_release -r -i -s | xargs echo
	/usr/bin/lsb_release -a 2>/dev/null
elif [ -f /etc/redhat-release ]; then
	cat /etc/redhat-release
elif [ -f /etc/gentoo-release ]; then
	cat /etc/gentoo-release
elif [ -f /etc/debian_version ]; then
	echo -n "Debian "
	cat /etc/debian_version
elif [ -f /etc/S?SE-release ]; then
	cat /etc/S?SE-release
elif [ -f /etc/slackware-version ]; then
	cat /etc/slackware-version
elif [ -f /etc/mandrake-release ]; then
	cat /etc/mandrake-release
elif [ -f /etc/fedora-release ]; then
	cat /etc/fedora-release
elif [ -f /etc/arch-release ]; then
	cat /etc/arch-release
fi
echo "[uptime]"
uptime
echo "[who]"
who
echo "[df]"
EXCLUDES=`cat /proc/filesystems | grep nodev | grep -v rootfs | awk '{print $2}' | xargs echo | sed -e 's! ! -x !g'`
ROOTFS=`readlink -m /dev/root`
df -Pl -x iso9660 -x $EXCLUDES | sed -e '/^[^ 	][^ 	]*$/{
N
s/[ 	]*\n[ 	]*/ /
}' -e "s&^rootfs&${ROOTFS}&"
echo "[inode]"
df -Pil -x iso9660 -x $EXCLUDES | sed -e '/^[^ 	][^ 	]*$/{
N
s/[ 	]*\n[ 	]*/ /
}' -e "s&^rootfs&${ROOTFS}&"
echo "[mount]"
mount
echo "[free]"
free

# TODO detect if ifconfig is present
echo "[ifconfig]"
/bin/ifconfig 2>/dev/null

PORTS_DONE=0
# /sbin/ss on gentoo
# /usr/bin/ss on bookworm
if [ -x /sbin/ss -o -x /usr/bin/ss ];then
	echo "[ss]"
	ss -tlpn
	PORTS_DONE=1
fi

# TODO detect if netstat is present
if [ -x /bin/netstat ];then
	echo "[route]"
	netstat -rn
	echo "[netstat]"
	netstat -s
	if [ $PORTS_DONE -eq 0 ];then
		echo "[ports]"
		# Bug in RedHat's netstat spews annoying error messages. 
		netstat -antu 2>/dev/null
	fi
fi

echo "[ifstat]"
/bin/ifconfig 2>/dev/null

if [ -x /bin/ip ];then
	echo '[iproute2_route]'
	ip route
	echo '[iproute2_stat]'
	ip -s link show
fi
# Report mdstat data if it exists
if test -r /proc/mdstat; then echo "[mdstat]"; cat /proc/mdstat; fi
if test -x /usr/bin/sensors
then
	echo "[lmsensors]"
	sensors
fi
if test -x /sbin/pvs
then
	echo "[lvm_pvs]"
	pvs
fi
if test -x /sbin/vgs
then
	echo "[lvm_vgs]"
	vgs
fi
echo "[ps]"
ps -Aww f -o pid,ppid,user,start,state,pri,pcpu,time:12,pmem,rsz:10,vsz:10,cmd

# $TOP must be set, the install utility should do that for us if it exists.
TOP=/usr/bin/top
if test "$TOP" != ""
then
    if test -x "$TOP"
    then
        echo "[top]"
	export CPULOOP ; CPULOOP=1 ;
	$TOP -b -n 1 
	# Some top versions do not finish off the last line of output
	echo ""
    fi
fi
echo "[vmstat]"
vmstat

echo '[clientversion]'
# to be changed by package manager
CLIENTVERSION=""
if [ -z "$CLIENTVERSION" ];then
	echo "xython-client"
else
	echo "xython-client-$CLIENTVERSION"
fi
# vgs --units=k
