#!/bin/sh

export LANG=C
export LC_ALL=C
SERVEROSTYPE="$(uname -s | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ/' 'abcdefghijklmnopqrstuvwxyz_')"	# This systems operating system in lowercase
MACHINEDOTS="$(uname -n)"

echo "client $MACHINEDOTS.$SERVEROSTYPE $SERVEROSTYPE"
echo "[date]"
date
echo "[uname]"
uname -rsmn
echo "[osversion]"
if [ -x /bin/lsb_release ]; then
	/bin/lsb_release -r -i -s
	/bin/lsb_release -a 2>/dev/null
elif [ -x /usr/bin/lsb_release ]; then
	/usr/bin/lsb_release -r -i -s
	/usr/bin/lsb_release -a 2>/dev/null
elif [ -f /etc/redhat-release ]; then
	cat /etc/redhat-release
elif [ -f /etc/gentoo-release ]; then
	cat /etc/gentoo-release
elif [ -f /etc/debian_version ]; then
	echo "Debian $(cat /etc/debian_version)"
elif [ -f /etc/SuSE-release ]; then
	# deprecated since 13.1 and removed since 15.0
	# https://en.opensuse.org/Etc_SuSE-release
	cat /etc/SuSE-release
elif [ -f /etc/slackware-version ]; then
	cat /etc/slackware-version
elif [ -f /etc/mandrake-release ]; then
	cat /etc/mandrake-release
elif [ -f /etc/fedora-release ]; then
	cat /etc/fedora-release
elif [ -f /etc/arch-release ]; then
	cat /etc/arch-release
fi

echo "[uptime]"
uptime

# on libreelec, no who
echo "[who]"
who

SIMPLE_DF=1
case $(uname) in
Linux)
	# detect busybox df
	df --help 2>&1| grep -qi busybox
	if [ $? -ne 0 ];then
		SIMPLE_DF=0
	fi
;;
esac

echo "[df]"
if [ $SIMPLE_DF -eq 1 ];then
	df
else
EXCLUDES=$(grep nodev /proc/filesystems | grep -v rootfs | awk '{print $2}' | xargs echo | sed -e 's! ! -x !g')
if [ -e /dev/root ];then
	# readlink -m do not work with busybox
	ROOTFS=$(readlink -m /dev/root)
else
	ROOTFS='unset'
fi

# TODO busybox does not like -l
# TODO FreeBSD does not like -x
df -Pl -x iso9660 -x "$EXCLUDES" | sed -e '/^[^ 	][^ 	]*$/{
N
s/[ 	]*\n[ 	]*/ /
}' -e "s&^rootfs&${ROOTFS}&"

# busybox does not support -i
echo "[inode]"
df -Pil -x iso9660 -x "$EXCLUDES" | sed -e '/^[^ 	][^ 	]*$/{
N
s/[ 	]*\n[ 	]*/ /
}' -e "s&^rootfs&${ROOTFS}&"
fi
#end !busybox

echo "[mount]"
mount


# BSD does not have free
case $(uname) in
Linux)
echo "[free]"
free
;;
FreeBSD)
TOTAL=$(sysctl -n hw.physmem)
#USER=$(sysctl -n hw.usermem)
#PAGESIZE=$(sysctl -n hw.pagesize)
FREE=$(sysctl vm.vmtotal|grep 'Free Memory' | grep -o '[0-9]*')
#echo "               total        used        free      shared  buff/cache   available"
#echo "Mem:     $TOTAL    $(($TOTAL-$USER))     $USER    $USER    $USER     $USER"
echo "[meminfo]"
echo "Total:$((TOTAL/1048576))"
echo "Free:$((FREE/1024))"
echo "[swapinfo]"
swapinfo -k
echo "[vmtotal]"
sysctl vm.vmtotal
;;
OpenBSD)
TOTAL=$(sysctl -n hw.physmem)
#echo "[meminfo]"
echo "Total:$((TOTAL/1048576))"
#echo "Free:$((FREE/1024))"
;;
esac

# TODO detect if ifconfig is present
echo "[ifconfig]"
case $(uname) in
Linux)
/bin/ifconfig 2>/dev/null
;;
OpenBSD)
ifconfig -A
;;
FreeBSD)
ifconfig -a
;;
esac

PORTS_DONE=0
# /sbin/ss on gentoo
if [ -x /sbin/ss ];then
	HAVE_SS=1
fi
# /usr/bin/ss on bookworm
if [ -x /usr/bin/ss ];then
	HAVE_SS=1
fi
if [ $HAVE_SS -eq 1 ];then
	echo "[ss]"
	ss -antup
	PORTS_DONE=1
fi

# TODO detect if netstat is present
if [ -x /bin/netstat ];then
	echo "[route]"
	netstat -rn
	echo "[netstat]"
	# busybox does not like -s
	netstat -s
	if [ $PORTS_DONE -eq 0 ];then
		echo "[ports]"
		# Bug in RedHat's netstat spews annoying error messages. 
		netstat -antu 2>/dev/null
		PORTS_DONE=1
	fi
fi
if [ $PORTS_DONE -eq 0 ];then
	case $(uname) in
	OpenBSD)
		echo "[ports]"
		netstat -na -f inet; netstat -na -f inet6
	;;
	FreeBSD)
		echo "[ports]"
		netstat -Wna -f inet; netstat -Wna -f inet6
	;;
	esac
fi

echo "[ifstat]"
case $(uname) in
Linux)
/bin/ifconfig 2>/dev/null
;;
OpenBSD)
	netstat -i -b -n | grep -Ev "^lo|<Link"
;;
FreeBSD)
	netstat -ibnW | grep -E "<Link|Name" | grep -v ^lo
;;
esac

if [ -x /bin/ip ];then
	echo '[iproute2_route]'
	ip route
	echo '[iproute2_stat]'
	ip -s link show
fi
# Report mdstat data if it exists
if test -r /proc/mdstat; then echo "[mdstat]"; cat /proc/mdstat; fi
if test -x /usr/bin/sensors
then
	echo "[lmsensors]"
	sensors
fi
if test -x /sbin/pvs
then
	echo "[lvm_pvs]"
	pvs
fi
if test -x /sbin/vgs
then
	echo "[lvm_vgs]"
	vgs
fi
case $(uname) in
Linux)
# busybox does not like -w
echo "[ps]"
ps -Aww f -o pid,ppid,user,start,state,pri,pcpu,time:12,pmem,rsz:10,vsz:10,cmd
;;
FreeBSD)
	ps -axd -ww -o pid,ppid,user,start,state,pri,pcpu,cputime,pmem,rss,vsz,command
;;
OpenBSD)
	ps -ax -ww -o pid,ppid,user,start,state,pri,pcpu,cputime,pmem,rss,vsz,args
;;
*)
	ps -Aww -o pid,ppid,user,start,state,pri,pcpu,time:12,pmem,rsz:10,vsz:10,cmd
;;
esac

# $TOP must be set, the install utility should do that for us if it exists.
TOP=/usr/bin/top
if test "$TOP" != ""
then
    if test -x "$TOP"
    then
        echo "[top]"
	case $(uname) in
	Linux)
	export CPULOOP ; CPULOOP=1 ;
	$TOP -b -n 1 
	# Some top versions do not finish off the last line of output
	echo ""
	;;
	FreeBSD)
	$TOP -n 20
	;;
	OpenBSD)
	$TOP -n 20
	;;
	esac
    fi
fi

# no vmstat on LibreELEC
echo "[vmstat]"
vmstat

echo '[clientversion]'
# to be changed by package manager
CLIENTVERSION=""
if [ -z "$CLIENTVERSION" ];then
	echo "xython-client"
else
	echo "xython-client-$CLIENTVERSION"
fi
# vgs --units=k
