.TH xython 5 "22 August 2023" "0.1.3" "xython 0.1.3"


.SH "NAME"
\fB
\fB
\fB
xython.cfg \fP\- xython server configuration file
\fB
.SH "SYNOPSIS"

\fBxython.cfg

.SH "FILE FORMAT"

\fBxython.cfg\fP uses a simple VARIABLE=value

.SH "OPTIONS"

.TP
.B PKIA_USER=pikauser
The username used to connect to a rabbitMQ server

.TP
.B PIKA_PASSWORD=pikapass
The password used to connect to a rabbitMQ server

.TP
.B XYTHON_TLS_KEY=keypath
Use keypath for finding certificate to use with xython-tlsd

.TP
.B XYTHON_TLS_CRT=crtpath
Use crtpath for finding certificate to use with xython-tlsd

.SH "SEE ALSO"

xython-tlsd(8)

.SH "LICENSING"
xython is licensed under the GPL v2 license and under development by LABBE Corentin.

.SH "CONTACT INFORMATION"

All contacts informations could be found at https://github.fr/xython-monitoring/xython/

