.TH xython-tlsd 8 "22 August 2023" "0.1.3" "xython 0.1.3"


.SH "NAME"
\fB
\fB
\fB
xythond \fP\- xython core server
\fB
.SH "SYNOPSIS"

\fBxython-tlsd
.RB [\-\-debug(\-d)]
.RB [\-\-help(\-h)]
.RB [\-\-daemon]
.RB [\-\-ipv6]
.RB [\-\-tload]
.RB [\-\-dump
.RB [\-\-xython
.IR level ]
.RB [\-\-netport
.IR netport ]
.RB [\-\-etcdir
.IR PATH ]
.RB [\-\-logdir
.IR PATH ]
.RB [\-\-debugs
.IR dbg1,dbg2 ]

.SH "DESCRIPTION"

\fBxythond\fP main xython process

.SH "OPTIONS"

.TP
.B \-\-debug
Enable more debugging

.TP
.B \-\-netport port
Listen on port "port" instead of the default (which is 1984).

.TP
.B \-\-etcdir PATH
Use PATH for search xython config directory

.TP
.B \-\-logdir PATH
Use PATH for storing log instead of default (TODO)

.TP
.B \-\-debugs dbg1,dbg2,...
Enable extra debug for a list of topic separated by comma.
.br
Example: --debugs rrd,loadgraph will add extra debug for rrd and loadgraph topic

.SH "EXAMPLES"
.B xythond --netport 2023 --etcdir /etc/tests

This command will ran xythond with a config set in /etc/tests/xython.cfg.
It will listen on port 2023.


.SH "LICENSING"
xython is licensed under the GPL v2 license and under development by LABBE Corentin.

.SH "CONTACT INFORMATION"

All contacts informations could be found at https://github.fr/xython-monitoring/xython/

